### ISSUE TITLE
On Android plugin crashes repeatedly when location permissions are not enabled

### ISSUE THREAD

**Issue by shamilovtim** [oracle/pushiomanager-react-native#11]
The docs do not explain handling notification permissions and the plugin upon initial load crashes because notification permissions are not yet enabled. The plugin attempts to request permissions but still crashes several times before it's able to successfully request them. When disabling notifications from the Settings panel of the phone, the app will crash every single time it is opened until notification permissions are enabled again.

Is Oracle aware of any users using this project in production? It seems like in its current state this project couldn't be live so I just want some clarity on whether you've ever had this plugin work for a customer.

Crash message:
```
2021-05-28 18:57:31.519 6271-6271/com.shipt.groceries E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.shipt.groceries, PID: 6271
    java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
        at com.pushio.manager.PIOPermissionsActivity.onRequestPermissionsResult(PIOPermissionsActivity.java:54)
        at android.app.Activity.requestPermissions(Activity.java:4579)
        at androidx.core.app.ActivityCompat.requestPermissions(ActivityCompat.java:502)
        at com.pushio.manager.PIOPermissionsActivity.processIntent(PIOPermissionsActivity.java:47)
        at com.pushio.manager.PIOPermissionsActivity.onNewIntent(PIOPermissionsActivity.java:22)
        at android.app.Activity.performNewIntent(Activity.java:7339)
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1366)
        at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1378)
        at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3295)
        at android.app.ActivityThread.performNewIntents(ActivityThread.java:3311)
        at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3328)
        at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6990)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
        ```

**Comment by neerhaj** [comment]
Please share your device model and OS version.

**Comment by shamilovtim** [comment]
Samsung Galaxy Note 9 
Android 9

**Comment by neerhaj** [comment]
Based on our investigation, this issue is only seen with the debug build. It is caused by the Hot Reload feature of React Native.

Since this issue is not seen in the release build, end-users should not be affected by this issue.

Developers can avoid this issue during development by,
- keeping the device location service On during development, or,
- calling `registerApp(false)` for debug builds.

**Comment by shamilovtim** [comment]
Thanks @neerhaj. I see there is also a 6.49 release. Do you know what has changed in that one?

**Comment by neerhaj** [comment]
This plugin is not yet compatible with 6.49 native SDK. So, please continue to use the 6.48.x native SDKs.

**Comment by shamilovtim** [comment]
We have upgraded this release to 6.48.1 and will let you know if that resolves it
