### ISSUE TITLE
Background messages only work if the message priority is set to 'high'

### ISSUE THREAD

**Issue by giovanijfc** [oracle/pushiomanager-react-native#59]
Hello, I updated my react-native from version 0.66.3 to 0.69.5 and notifications on Android are not showing, iOS works normally.

Found this error in Android Studio Logcat:

`
2022-09-22 16:51:46.996 9240-9240/com.app E/RNFirebaseMsgReceiver: Background messages only work if the message priority is set to 'high'
    android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=com.app/io.invertase.firebase.messaging.ReactNativeFirebaseMessagingHeadlessService (has extras) }: app is in background uid UidRecord{b3a7cf6 u0a870 RCVR idle change:idle|uncached procs:0 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1941)
        at android.app.ContextImpl.startService(ContextImpl.java:1887)
        at android.content.ContextWrapper.startService(ContextWrapper.java:793)
        at android.content.ContextWrapper.startService(ContextWrapper.java:793)
        at io.invertase.firebase.messaging.ReactNativeFirebaseMessagingReceiver.onReceive(ReactNativeFirebaseMessagingReceiver.java:55)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4843)
        at android.app.ActivityThread.access$1800(ActivityThread.java:315)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2297)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8751)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
`

**Comment by JulioCVaz** [comment]
the same here @neerhaj some solution?

**Comment by adniltonsantos** [comment]
heloo @JulioCVaz , aaah tu eh brasileiro , já ia mandar um INGLESHAO aqui kkk

https://github.com/oracle/pushiomanager-react-native/wiki/Android:-Handling-Push-Notifications-In-App-Background-or-Killed-State

cara tenta isso, tivemos o mesmo problema aqui na empresa e resolvemos com isso. 

Qualquer coisa me chama. boa sorte .

**Comment by JulioCVaz** [comment]
Maravilha @adniltonsantos! Obrigado por compartilhar! Vamos implementar. 🤝

**Comment by adniltonsantos** [comment]
@giovanijfc , teste isso 

try this
https://github.com/oracle/pushiomanager-react-native/wiki/Android:-Handling-Push-Notifications-In-App-Background-or-Killed-State

Solved it for me , But if you use Firebase push, I'm having a problem with multiple Oracle notification pushes

------------

@JulioCVaz  , se voce utiliza firebase , tome cuidado ... estou tendo problema com multiplos envios de notificacao da sdk da oracle apos ter recebido pelo menos uma notificacao de push do firebase , abrindo um chamado pra eles verem isso..

**Comment by AndriySikora** [comment]
The issue is solvable with those changes - https://github.com/oracle/pushiomanager-react-native/wiki/Android:-Handling-Push-Notifications-In-App-Background-or-Killed-State

It is not recommended to set priority to 'High', but in case it is needed please check following docs:

- https://docs.oracle.com/en/cloud/saas/marketing/responsys-user/Push_Design.htm#:~:text=Sending%20high%20priority%20messages%20to%20Android%20devices

- https://docs.oracle.com/en/cloud/saas/marketing/responsys-user/Push_Designer.htm

Set 'High' priority messages for Android platform should be requested from Oracle.
