### ISSUE TITLE
NullPointerException when using @oracle/react-native-pushiomanager on Android

### ISSUE THREAD

**Issue by sorarco** [oracle/pushiomanager-react-native#72]
**Issue Description**:
We are encountering a NullPointerException when using the @oracle/react-native-pushiomanager module, version ^6.52.2, in our React Native application. This issue is specific to Android devices and may potentially be related to in-app messages.

**The error stack trace is as follows**:
`
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
    at com.pushio.manager.r0.F(SourceFile:1)
    at com.pushio.manager.c0.o(SourceFile:1)
    at com.pushio.manager.c0.e(SourceFile:1)
    at com.pushio.manager.c0$a$a.run(Unknown Source:9)
    at java.lang.Thread.run(Thread.java:1012)
`

The error seems to be occurring during the handling of a bitmap operation inside the PushIOManager.

**Steps to Reproduce**:
Install @oracle/react-native-pushiomanager version ^6.52.2.
Set up in-app messaging for the Android platform.
Trigger a push notification or an in-app message on an Android device.
Observe the crash with the aforementioned stack trace.
Expected Behavior:
The push notification or in-app message should be displayed without causing a crash.

**Actual Behavior**:
The app crashes with a NullPointerException when trying to access a Bitmap object during push or in-app message handling.

**Affected Environment**:
Library Version: @oracle/react-native-pushiomanager@^6.52.2
**Platform**: Android
**React Native Version**: 0.73.8
**Device Information**: Occurs across multiple Android devices.
**Additional Information**: _We suspect that the issue might be related to handling in-app messages, but further investigation is needed to confirm this._

Please advise if there are any known fixes or workarounds for this issue. 
Could this be related to improper bitmap handling in in-app messages? 
Any guidance on this matter would be greatly appreciated.

Thank you!

**Comment by brqlfreitas** [comment]
We’re seeing the same crash on @oracle/react-native-pushiomanager 6.56.4.

  Stack:
  PIONotificationManager.tintImage -> Bitmap.getWidth() `  Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
       at com.pushio.manager.PIONotificationManager.tintImage(PIONotificationManager.java:630)
       at com.pushio.manager.PIOFCMAsyncTask.notifyUser(PIOFCMAsyncTask.java:495)
       at com.pushio.manager.PIOFCMAsyncTask.access$200(PIOFCMAsyncTask.java:52)
       at com.pushio.manager.PIOFCMAsyncTask$1$1.run(PIOFCMAsyncTask.java:123)
       at java.lang.Thread.run(Thread.java:1119)`

  Environment:
  - React Native: 0.74.2
  - Android: compileSdk 36, targetSdk 36, minSdk 23, buildTools 35.0.0
  - AGP: 8.9.1 / Gradle: 8.11.1
  - Kotlin: 1.8.22
  - Hermes: enabled
  - PushIO native: local AAR PushIOManager-6.56.6
  - Firebase: RN Firebase 20.4.0, BOM 31.0.2 (explicit firebase-messaging 17.3.0 in app build.gradle)

  Occurrence:
  - High frequency across multiple devices and Android versions
