### ISSUE TITLE
TypeError: null is not an object (evaluating 'RCTPushIOManager.configure')

### ISSUE THREAD

**Issue by niltoneapontes** [oracle/pushiomanager-react-native#9]
Hi there. I've been getting this error when trying to use PushIOManager in my react-native expo project.

``` 
TypeError: null is not an object (evaluating 'RCTPushIOManager.registerApp')
at node_modules\react-native\Libraries\LogBox\LogBox.js:148:8 in registerError
at node_modules\react-native\Libraries\LogBox\LogBox.js:59:8 in errorImpl
at node_modules\react-native\Libraries\LogBox\LogBox.js:33:4 in console.error
at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:104:6 in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:171:19 in handleException
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:24:6 in handleError
at node_modules\expo-error-recovery\build\ErrorRecovery.fx.js:9:32 in ErrorUtils.setGlobalHandler$argument_0
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:293:29 in invoke
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:154:27 in invoke
at node_modules\regenerator-runtime\runtime.js:164:18 in PromiseImpl.resolve.then$argument_0
at node_modules\react-native\node_modules\promise\setimmediate\core.js:37:13 in tryCallOne
at node_modules\react-native\node_modules\promise\setimmediate\core.js:123:24 in setImmediate$argument_0
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:130:14 in _callTimer
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:181:14 in _callImmediatesPass
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:441:30 in callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:387:6 in __callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:135:6 in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:134:4 in flushedQueue
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue
```

This is my "app" structure with the two downloaded files already placed.
![image](https://user-images.githubusercontent.com/59576458/119705656-66100b80-be2f-11eb-8ab9-d46954ff0351.png)

This is my AndroidManifest.xml file:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.project">
  <uses-permission android:name="android.permission.INTERNET"/>
  <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
  <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
  <uses-permission android:name="android.permission.USE_FINGERPRINT"/>
  <uses-permission android:name="android.permission.USE_BIOMETRIC"/>
  <uses-permission android:name="android.permission.VIBRATE"/>
  <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS"/>
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
  <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>
  <uses-permission android:name="android.permission.CAMERA"/>
  <uses-permission android:name="android.permission.RECORD_AUDIO"/>
  <uses-permission android:name="android.permission.READ_CONTACTS"/>
  <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
  <uses-permission android:name="android.permission.READ_CALENDAR"/>
  <uses-permission android:name="android.permission.WRITE_CALENDAR"/>
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
  <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="${applicationId}.permission.PUSHIO_MESSAGE" />
  <uses-permission android:name="${applicationId}.permission.RSYS_SHOW_IAM" />
  <permission android:name=".permission.PUSHIO_MESSAGE" android:protectionLevel="signature" />
  <permission android:name="${applicationId}.permission.RSYS_SHOW_IAM" android:protectionLevel="signature" />
  <application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round" android:allowBackup="false" android:theme="@style/AppTheme">
    <meta-data android:name="expo.modules.updates.EXPO_SDK_VERSION" android:value="40.0.0"/>
    <meta-data android:name="expo.modules.updates.ENABLED" android:value="true"/>
    <meta-data android:name="expo.modules.updates.EXPO_UPDATES_CHECK_ON_LAUNCH" android:value="ALWAYS"/>
    <meta-data android:name="expo.modules.updates.EXPO_UPDATES_LAUNCH_WAIT_MS" android:value="0"/>
    <activity android:name=".MainActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" android:launchMode="singleTask" android:windowSoftInputMode="adjustResize" android:theme="@style/Theme.App.SplashScreen">
      <intent-filter>
        <action android:name="android.intent.action.MAIN"/>
        <category android:name="android.intent.category.LAUNCHER"/>
      </intent-filter>
      <intent-filter>
        <action android:name="${applicationId}.NOTIFICATIONPRESSED" />
        <category android:name="android.intent.category.DEFAULT" />
      </intent-filter>
    </activity>
    <activity android:name="com.facebook.react.devsupport.DevSettingsActivity"/>
    <receiver android:enabled="true" android:exported="false" android:name="com.pushio.manager.PushIOUriReceiver" tools:node="replace">
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <data android:scheme="@string/uri_identifier" />
      </intent-filter>
    </receiver>
    <activity android:name="com.pushio.manager.iam.ui.PushIOMessageViewActivity" android:permission="${applicationId}.permission.SHOW_IAM" android:theme="@android:style/Theme.Translucent.NoTitleBar">
      <intent-filter tools:ignore="AppLinkUrlError">
      <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.BROWSABLE" />
        <category android:name="android.intent.category.DEFAULT" />
        <data android:scheme="@string/uri_identifier" />
      </intent-filter>
    </activity>
  </application>
</manifest>
```

My strings.xml:

```
<resources>
    <string name="app_name">myProjectName</string>
    <string name="uri_identifier">pio-My_API_KEY</string>
</resources>
```

I've added the lib in my project using `yarn add https://github.com/oracle/pushiomanager-react-native.git` and also put this code in my App.js file: 

```
import PushIOManager from 'react-native-pushiomanager';

if(Platform.OS === 'android') {
  PushIOManager.registerApp(true, (error, response) => {	
    
  });
} else {
  PushIOManager.registerForAllRemoteNotificationTypes((error, response) => {

    PushIOManager.registerApp(true, (error, response) => {

    });
});
}

PushIOManager.configure("pushio_config.json", (error, response) => {
  if(error) {
    console.log(error);
  } else {
    console.log(response);
  }
});
```

PS.: If I put only the configure function, I still get:

```
TypeError: null is not an object (evaluating 'RCTPushIOManager.configure')
at node_modules\react-native\Libraries\LogBox\LogBox.js:148:8 in registerError
at node_modules\react-native\Libraries\LogBox\LogBox.js:59:8 in errorImpl
at node_modules\react-native\Libraries\LogBox\LogBox.js:33:4 in console.error
at node_modules\expo\build\environment\react-native-logs.fx.js:27:4 in error
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:104:6 in reportException
at node_modules\react-native\Libraries\Core\ExceptionsManager.js:171:19 in handleException
at node_modules\react-native\Libraries\Core\setUpErrorHandling.js:24:6 in handleError
at node_modules\expo-error-recovery\build\ErrorRecovery.fx.js:9:32 in ErrorUtils.setGlobalHandler$argument_0
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:293:29 in invoke
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:154:27 in invoke
at node_modules\regenerator-runtime\runtime.js:164:18 in PromiseImpl.resolve.then$argument_0
at node_modules\react-native\node_modules\promise\setimmediate\core.js:37:13 in tryCallOne
at node_modules\react-native\node_modules\promise\setimmediate\core.js:123:24 in setImmediate$argument_0
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:130:14 in _callTimer
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:181:14 in _callImmediatesPass
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:441:30 in callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:387:6 in __callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:135:6 in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:134:4 in flushedQueue
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue
```

Does it have to do with the fact that I'm using expo or is there something I should have done and didn't?

**Comment by niltoneapontes** [comment]
Update: I've created a blank project with `npx react-native init projectName` and done the same process of adding downloaded files and a few code lines to AndroidManifest.xml and strings.xml. 

![image](https://user-images.githubusercontent.com/59576458/119711261-b38f7700-be35-11eb-9b64-86ed261acdca.png)

I keep getting the same error, even though I'm not using Expo anymore.

**Comment by neerhaj** [comment]
Could you share the blank project that is giving this error?

**Comment by niltoneapontes** [comment]
Sure, here it is:

https://github.com/niltoneapontes/simple-project-responsys

PS.: I've changed the info on _pushio_config.json_ in order to maintain my client's privacy. Please just replace it with a working one.

**Comment by neerhaj** [comment]
The blank project does not have the plugin integrated. Could you update the code with the plugin integration?

**Comment by niltoneapontes** [comment]
Oh, I am very sorry. I forgot to push my changes before sending the link. It's been updated now.

**Comment by niltoneapontes** [comment]
Hi, there. Turns out the problem was with the package name in one of my files. I changed it to the correct one and it works perfectly on Android. 

When trying to run on iOS, I get the error 
```
In file included from /Users/app/Documents/app-chinaInBox/app-chinaInBox/node_modules/react-native-pushiomanager/ios/NSArray+PIOConvert.m:9:
/Users/app/Documents/app-chinaInBox/app-chinaInBox/node_modules/react-native-pushiomanager/ios/NSDictionary+PIOConvert.h:9:9: fatal error: 'PushIOManager/PushIOManagerAll.h' file not found
#import <PushIOManager/PushIOManagerAll.h>
```

I've put PushIOManager.framework inside the PushIOManager folder in the plugin folder:
![image](https://user-images.githubusercontent.com/59576458/121741608-2145cf00-cad5-11eb-81b2-0657140355fd.png)

And also added the path into my Podfile and run `pod install`
![image](https://user-images.githubusercontent.com/59576458/121741868-75e94a00-cad5-11eb-8402-d2ec59c42745.png)

**Comment by s-wasan** [comment]
could you please verify `PushIOManager.framework` available in the `../node_modules/rect-native-pushiomanager/PushIOManager/` directory.

You need to copy the `PushIOManager.framework`  in the `../node_modules/rect-native-pushiomanager/PushIOManager/` directory.
